### PR TITLE
Update tests to validate only expected behavior

### PR DESCRIPTION
**Pull request by Alex-J-W**
As implementing tests one by one i got confused as to why the test_init would complaint about the method `build_word_frequencies` not being implemented yet and the error actually stemmed from the test fixture.  For this reason I would propose to move the call to `build_word_frequencies`  to the corresponding test, slim down the test fixture (if needed at all) and simplify test_init

### CODE REVIEW

**Review by pkeilbach — CHANGES_REQUESTED** [review]
Indeed that is better test design, @Alex-J-W 🚀 

Looks good from implementation, but the formatter currently complains. Please run `make format` locally to fix it!

**Review by pkeilbach — DISMISSED** [review]
LGTM! One bonus point for you, @Alex-J-W 🏆

**Comment by Alex-J-W** [comment]
Since the PR wasn't merged yet i thought i can add my oversight here directly. I forgot to call `build_word_frequencies` in `test_get_features` to be able to perform the correct assertion.

**Review by pkeilbach — DISMISSED** [review]
LGTM! 🚀 

We could even think about adding another fixture that comes with the built word frequencies:

```python
@pytest.fixture
def vectorizer_initialiued(vectorizer):
    return vectorizer.build_word_frequencies(tweets, labels)
```

Then, the tests can use this fixture: 
```
def test_build_word_frequencies(vectorizer_initialized):
    assert ...
```

I will approve as is, but if you want you can make this little refactoring a follow-up 😉

**Review by pkeilbach — APPROVED** [review]
LGTM! A well deserved bonus point, @Alex-J-W 🚀

**Comment by pkeilbach** [comment]
with follow up I meant you can earn another bonus point. But since you incorporated it in this PR, I will give you a second bonus point for this. That makes two in total for this PR 🏅

**Pull request merged**
