### PR TITLE
Add precommit strip ipynb

### PR DESCRIPTION
**Pull request by TobiTgl**
Add precommit strip ipynb to remove results of running the python notebook.

### CODE REVIEW

**Comment by TobiTgl** [comment]
I think its failing because there are still some outputs on main currently?

**Comment by pkeilbach** [comment]
> I think its failing because there are still some outputs on main currently?

Yes, I think you will need to update all notebooks as well to make the pipeline work, otherwise the introduces hook will always fail. You can test if everything works locally using `make check-pre-commit` command

image

**Comment by TobiTgl** [comment]
I removed the outputs, looks like it's working now 👍

**Comment by pkeilbach** [comment]
closes #191

**Review by pkeilbach — APPROVED** [review]
LGTM!

**Pull request merged**
